version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: FI4
      MYSQL_USER: hesam
      MYSQL_PASSWORD: Camera20!!@@##$$
    ports:
      - "3306:3306"